# Nombre de la aplicacion
spring.application.name=topsell-backend

# Conexion a Base de Datos
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracion de Tomcat
server.tomcat.threads.max=40
server.tomcat.threads.min-spare=5
server.tomcat.accept-count=20

# Configuracion de HikariCP
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Configuracion de Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


# Configuracion Resend - Quotes
resend.api-key=${RESEND_API_KEY}
resend.from.email.quotes={RESEND_FROM_EMAIL_QUOTES}

resend.from.email.contact = ${RESEND_FROM_EMAIL_CONTACT}
resend.admin.email.contact = ${RESEND_ADMIN_EMAIL_CONTACT}

# Configuracion de Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Configuracion de Google reCAPTCHA v3
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY}
recaptcha.min-score=${RECAPTCHA_MIN_SCORE}

# Configuracion de JWT
jwt.secret.key=${JWT_SECRET_KEY}
# Duracion del token en milisegundos
jwt.expiration.ms=${JWT_EXPIRATION_MS}

# Configuracion de carga de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Configuracion basica de API
server.port=${PORT:8080}
